In [28]:
import numpy as np

In [29]:
## numpy는 한가지 문자열만을 담을 수 있음 ##

a = [1, 2, 3, 4, 5]
b = np.array(a)

print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [30]:
b1 = np.arange(1, 10, 2)

print(b1)

[1 3 5 7 9]


In [31]:
a2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b2 = np.array(a2)

print(a2)
print(b2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
a3 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b3 = np.array(a3).reshape(3, 3)

print(a3)
print(b3)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
print(b3[0][1])
print(b3[::-1, 1])

2
[8 5 2]


In [50]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(11, 20).reshape(3, 3)
print(arr1)
print(arr2)

print(arr1 + arr2)
print(arr1 * arr2)

print(arr1 * 2)

list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)
#print(list1 * list2)
print(list1 * 3)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
45


In [56]:
print(arr1.sum())
print(np.sum(arr1))
print(np.sum(arr1, axis=0))
print(np.sum(arr1, axis=1))
print(np.mean(arr1))

45
45
[12 15 18]
[ 6 15 24]
5.0


In [70]:
arr2 = [5, 4, 2, 3, 7, 1, 6, 9, 8]
numarr2 = np.array(arr2).reshape(3, 3)

print(numarr2)
print(np.sort(numarr2))
print(np.sort(numarr2, axis = 0))
print(np.sort(numarr2, axis = 1))
print("*****************************************")
print(np.sort(numarr2, axis = 0)[::-1, ::]) ## 열기준 행순서 역순
print(np.sort(numarr2, axis = 1)[::, ::-1]) ## 행기준 열순서 역순
print("*****************************************")
print(numarr2)
print(np.transpose(numarr2))

[[5 4 2]
 [3 7 1]
 [6 9 8]]
[[2 4 5]
 [1 3 7]
 [6 8 9]]
[[3 4 1]
 [5 7 2]
 [6 9 8]]
[[2 4 5]
 [1 3 7]
 [6 8 9]]
*****************************************
[[6 9 8]
 [5 7 2]
 [3 4 1]]
[[5 4 2]
 [7 3 1]
 [9 8 6]]
*****************************************
[[5 4 2]
 [3 7 1]
 [6 9 8]]
[[5 3 6]
 [4 7 9]
 [2 1 8]]


In [74]:
print(numarr2 >= 5)
print(np.all(numarr2) >= 5)

[[ True False False]
 [False  True False]
 [ True  True  True]]
False


In [78]:
zeros1 = np.zeros(10)
ones1  = np.ones(10)
print(zeros1)
print(ones1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [81]:
zeros2 = np.zeros([3, 3])
ones2  = np.ones([2, 4])

print(zeros2)
print(ones2)
print("**************************")
print(numarr2.shape)
zeros3 = np.zeros_like(numarr2)
ones3  = np.ones_like(numarr2)
print(zeros3)
print(ones3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
**************************
(3, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
